services:
  - type: web
    name: keracare-app
    env: node
    plan: free
    buildCommand: npm install --build-from-source=sqlite3
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
